---
apiVersion: tower.ansible.com/v1alpha1
kind: AnsibleJob
metadata:
  name: post-cluster
  namespace: cluster-management-ansible
  labels: 
    app.kubernetes.io/name: post-cluster
spec:
  tower_auth_secret: toweraccess
  job_template_name: create-db
