---
apiVersion: tower.ansible.com/v1alpha1
kind: AnsibleJob
metadata:
  name: prepare-cluster
  namespace: cluster-management-ansible
  labels: prepare-cluster
    app.kubernetes.io/name: 
spec:
  tower_auth_secret: toweraccess
  job_template_name: create-db
